language: generic
branches:
  only:
  - master
deploy:
  provider: s3
  access_key_id:
    secure: Kb5DavhLA+j0xqa7jRtOci9Sr4rcbeVmTMbgFErSe8r1LwC6CP1R0JD5T09X6Lx+EvrWJRVOqXJQ0dwHP0xOQMISNApNILY++oiiMf+JOQE9xiZA3C/IA7NqlI/RIGhmjD/1C7zJmpnVvhROFRt6zBBwoBXLr37ZlAhow0hR/Z00aL/WNnJK8K1axPUpRsGrBi900wwR4ppBMn0k0kHdGEXWHDcjIZIQdej9IiVYeqiIeRMf92OCAX10tgzOEg/DhaZer220MoUyex2A6KjYoeREKNx9VCrWivwEzdP6NQdmNylBKDswi+CCAKGhSyzfNfM7jRprmQmVjNquVXvuq+YYQ+/EqhADcAQekFueHxVuxxuftcqR6Fwxixo7T/ggabznAQ6rxqFg292YA++ZAfTM3jsa2RbSihChoZTWP1Aac05aS9tSZ7EFUyhHg/vcT1uKl0S1Q18buR4AZ4D3o1TBDlEbu6xTvTOsGPDyicfu9b6EtvKOa32bGdQpMohMUHnEDSD83BxJKgVjYTftky3zwXjRuyw/DVMdf+JsIoA9pX0eIdYsFDN3sRC8pfrfkd0R+w3bsX4Nx6Vou4Ji7jWlEyFmc5iQ4sfjMcl3AzmEF5ex02shQ8s9sWZp8IbS3ffZlXVHD44ZFPAoVe781eSz3FpLLSPcHL0A2X8ky0A=
  secret_access_key:
    secure: AhigN6pSqOA75HBQzotPNMsRy1WSb9rnv3Ue7aIPxkChyhessYfrB58my2wIuJJ85YcAEPtF2t/REhDmPQZ8nJofGeYn4FYhRqBMb6vkOa+mf24y93yczS5gvgCbiiTcs9vEm8YRaUdieK7GQN0YdHUeX4KCwkgCBHu/Z6DN0dwYA8cUjp0L3G9PtwHn3QrEdqS/4JaQUDSsJhroXeJkUMbeP73oxQSA19n5oBlM83wMal6TH0INfjiUCpFzJ2oEMu8bw2yQ9E2GH75ubkaFtQI2Cd8Lp15Ji+w/Biu0Shdv1EGlbeNaSzuEOAyYlmUTFXN/O/a+xIYT6Awh/wu80KVaOKdkLYKU1D/7V7VCHGjY+BU9iajP0w5p5jshj0mNsoVGRSDm00GdsFEfHEl/M8t0tczpXr1Gpz/Typ8dJwawpJ8XkGe1UTF9Dg4a3EclHSjT921IGQ8fHK67jgDBcGvdm9FacOYgr3TjseKfD69gqF4TUTackyipoxI9poGxPrSdpI4q4nhxUyf8QYtifvIaQfq15CCVaMe2TTRtsrFIqOBtbn4pM5zSav8bU7uePkMQt+Ve3+Y2pF6kzggWdowJcR+IGRnAhn1whLm6bHHwJo+8P/X4hvFoosZVaFtBHLuDl+dkg9YdPznhbEaJUgOphjvYd8CQlWOxaAngwFY=
  bucket: reedmartz.com
  cache_control: "max-age=604800"
notifications:
  email:
    on_failure: always
    on_success: always
