branches:
  only:
  - develop
deploy:
  provider: s3
  access_key_id:
    secure: a3q+8IEBnv5M4Xfo0RPP2r8wcWrmXv8yE9SQo6dlRVo27awbGt5rV7RI+Xp51KgEqodTIfxTnmgrPzeGHufrvPB8U5o5UdrvdeHh13hrW/LvawzREhJo+/c37yjKPAlF3NRA70t//bbBC/QdjTuNv/25veZYsb2UIn0OmcjsP8+K8/t95cxkKKgOIdBI2I/979tXQ66cU3G3D8JVJ74DHXlvJTsuUr7C3qlF6g1yxkIlWoGbuL8qM0wcBxP0N7hXl3ECddMsowe72zAegyfHyWm9f+y0pv7NYL45gjQ+9BCSAFweMv7NXRsENJi0cySezrU5E670W44O2hzIWiPpYXYg0ST9QVWXci7XRa58UGhYCfTf2204pMCIf2HSbbfKbdfh4Qk93Kuw3gGr0jW/N78f/wKotVgzC7y/jpsfUEJgwrq7zwNU4XtEV9e/+CcgWSXTrMNF+ch3W/J9KXx+AAbYhd4qAeOuIWJmoN5znpgpNCIxzyPcIrMJepjisWp3tnbFP8p8anRgJ1Cye3B/st8xSGxJvGjbiVyxRsChUVQLh/6m6WnQiMTkCtc2XuijKiJC96ygmyHRqfJ8aRQPlRkCUPRmzpnXPArCscfTaweYJfg72F9IWjYu4EXZTxpGi5Y4Y9aWpwcvTaDGERosX6r65wh5gUULLI7RuT/Hy48=
  secret_access_key:
    secure: Y74dlikAJ7xQaXMOFAq4znP7986YfCsZp3kH/+Rmazur2+AvD401Ei8D4FHg703dsJt/BYNej/NvbW153nVAWxcCtUxEONscCsCsbn92bywcz+F6m7xsudzOHfeV3aAVrAO5UUbNGvUPmiNKDV+nBGGcxLmewZFNX7n4pag+Bd2aSX1qIVt96jZ4L+4DwgcAvYRRgZcyzvByGlWW/GTVAjqvY6gU5LY085gM9VYRkyr1r9SwH2FdYIBj9ugEEAHLRU5z9CyCnV65ZvbSfDBuGaJ7mUNsui0uJ2Mg8Tu+CFRDdbrtlwceakrjmUFtuyfe7tpWMGJLb1k0NPWRqmslU0WFQsT9rj5S0XAUje2c65q2oRIVrWwZAPdSu0ImAIKYmApHhT1HH1vqWMkXFUwda6mXj//XbGPQmawvXEtUWNxGy2e10Gh0r3YMrGntkgFr7BkMchikHRn3tkB5KHnTTKaLaTD80gL+ev92tLv3tIOtsS4llaotXFourkidS/rotMEZ77y+24ArZsvUAXAy6Nok/8FZJIm1wPbgzqNswnrdMuAMppHmU1f8kgfBdsvwoyCMrjWt8VLFBFaK2Wiljt49jdkXMxsMkDTb8aY/+E9uC3Pi9YksR4NSro/eg7W30UijlVnW0qtjWaO+OPBAvwnFyma28XZZ58nsh9M/XOE=
  bucket: reedmartz.com
  on:
    branch: develop
notifications:
  email:
    on_failure: always
    on_success: always
